name: Test LiteLLM Anthropic

on:
  workflow_dispatch:

jobs:
  test-anthropic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install litellm

      - name: Test Anthropic Completion
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          python -c "
import os
os.environ['ANTHROPIC_API_KEY'] = os.getenv('ANTHROPIC_API_KEY')
from litellm import completion
messages = [{ 'role': 'user', 'content': 'Hallo, wie geht es dir?' }]
response = completion(model='claude-3-haiku-20240307', messages=messages)
print(response)
"
